# Configurazione ALSA per DAC I2S
# Sostituisci "card 0" con l'indice corretto del tuo DAC I2S
# Usa 'aplay -l' per trovare l'indice corretto.

pcm.!default {
    type hw
    card 0
}

ctl.!default {
    type hw
    card 0
}
